import type { Page } from '@playwright/test';
import type { Zone } from './types.js';

export const ZONE_ID_PREFIX = 'argo-overlay-';

const ZONE_POSITIONS: Record<Zone, Record<string, string>> = {
  'bottom-center': {
    position: 'fixed', bottom: '60px', left: '50%', transform: 'translateX(-50%)',
  },
  'top-left': {
    position: 'fixed', top: '40px', left: '40px',
  },
  'top-right': {
    position: 'fixed', top: '40px', right: '40px',
  },
  'bottom-left': {
    position: 'fixed', bottom: '60px', left: '40px',
  },
  'bottom-right': {
    position: 'fixed', bottom: '60px', right: '40px',
  },
  'center': {
    position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)',
  },
};

/**
 * Inject content into a zone. Replaces any existing overlay in that zone.
 * Security: contentHtml is generated by template renderers which escape all
 * text fields via escapeHtml(). Content originates from author-controlled
 * manifest files, not end-user input.
 */
export async function injectIntoZone(
  page: Page,
  zone: Zone,
  contentHtml: string,
  containerStyles: Record<string, string>,
  animationCSS?: string,
): Promise<void> {
  const zoneId = ZONE_ID_PREFIX + zone;
  const positionStyles = ZONE_POSITIONS[zone];
  const baseStyles: Record<string, string> = {
    ...positionStyles,
    zIndex: '999999',
    pointerEvents: 'none',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    ...containerStyles,
  };

  await page.evaluate(([id, html, styles, css]) => {
    const existing = document.getElementById(id);
    if (existing) existing.remove();

    if (css) {
      const styleId = id + '-style';
      let styleEl = document.getElementById(styleId) as HTMLStyleElement | null;
      if (!styleEl) {
        styleEl = document.createElement('style');
        styleEl.id = styleId;
        document.head.appendChild(styleEl);
      }
      styleEl.textContent = css;
    }

    const container = document.createElement('div');
    container.id = id;
    container.innerHTML = html;
    Object.assign(container.style, styles);
    document.body.appendChild(container);
  }, [zoneId, contentHtml, baseStyles, animationCSS ?? ''] as const);
}

export type BackgroundTheme = 'dark' | 'light';

/**
 * Detect whether the background at a zone's position is dark or light.
 * Samples the element at the zone coordinates, skipping fixed-position elements
 * (navbars, toolbars) to read the actual page content background.
 * Returns the *overlay* theme for contrast: dark bg → 'light' overlay, light bg → 'dark' overlay.
 */
export async function detectBackgroundTheme(page: Page, zone: Zone): Promise<BackgroundTheme> {
  const pos = ZONE_POSITIONS[zone];
  return page.evaluate((zonePos) => {
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    let x = vw / 2;
    let y = vh / 2;

    if (zonePos.left === '40px') x = 80;
    else if (zonePos.right === '40px') x = vw - 80;
    else if (zonePos.left === '50%') x = vw / 2;

    if (zonePos.top === '40px') y = 80;
    else if (zonePos.bottom === '60px') y = vh - 80;
    else if (zonePos.top === '50%') y = vh / 2;

    // Get all elements at this point, skip fixed-position ones (navs, toolbars)
    const elements = document.elementsFromPoint(x, y);

    for (const el of elements) {
      const style = getComputedStyle(el);
      // Skip fixed elements (navbars, overlays) — they don't represent page content
      if (style.position === 'fixed' || style.position === 'sticky') continue;

      const bg = style.backgroundColor;
      const match = bg.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/);
      if (match) {
        const [, r, g, b, a] = match;
        const alpha = a !== undefined ? parseFloat(a) : 1;
        if (alpha > 0.1) {
          const luminance = 0.299 * Number(r) + 0.587 * Number(g) + 0.114 * Number(b);
          return luminance < 128 ? 'light' as const : 'dark' as const;
        }
      }
    }

    // Fall back: resolve CSS custom properties used for backgrounds.
    // getComputedStyle(body).backgroundColor returns transparent when
    // the background is set via CSS variables (e.g., background: var(--bg)).
    // We resolve the variable value and parse the hex/rgb color.
    const rootStyle = getComputedStyle(document.documentElement);
    const bgVarNames = ['--bg', '--background', '--bg-color', '--background-color'];
    for (const varName of bgVarNames) {
      const varVal = rootStyle.getPropertyValue(varName).trim();
      if (!varVal) continue;
      // Try hex color
      const hexMatch = varVal.match(/^#([0-9a-f]{3,8})$/i);
      if (hexMatch) {
        let hex = hexMatch[1];
        if (hex.length === 3) hex = hex[0]+hex[0]+hex[1]+hex[1]+hex[2]+hex[2];
        const r = parseInt(hex.slice(0, 2), 16);
        const g = parseInt(hex.slice(2, 4), 16);
        const b = parseInt(hex.slice(4, 6), 16);
        const lum = 0.299 * r + 0.587 * g + 0.114 * b;
        return lum < 128 ? 'light' as const : 'dark' as const;
      }
      // Try rgb/rgba
      const rgbMatch = varVal.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
      if (rgbMatch) {
        const lum = 0.299 * Number(rgbMatch[1]) + 0.587 * Number(rgbMatch[2]) + 0.114 * Number(rgbMatch[3]);
        return lum < 128 ? 'light' as const : 'dark' as const;
      }
    }

    // Check if html/body has a class indicating dark mode
    const htmlClasses = document.documentElement.className;
    const bodyClasses = document.body.className;
    if (/\bdark\b/i.test(htmlClasses) || /\bdark\b/i.test(bodyClasses)) {
      return 'light' as const;
    }

    // Last resort: system theme
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    return prefersDark ? 'light' as const : 'dark' as const;
  }, pos);
}

/**
 * Remove the overlay in the specified zone, if any.
 */
export async function removeZone(page: Page, zone: Zone): Promise<void> {
  const zoneId = ZONE_ID_PREFIX + zone;
  await page.evaluate((id) => {
    document.getElementById(id)?.remove();
    document.getElementById(id + '-style')?.remove();
  }, zoneId);
}
