import type { Page } from '@playwright/test';
import type { Zone } from './types.js';

export const ZONE_ID_PREFIX = 'argo-overlay-';

const ZONE_POSITIONS: Record<Zone, Record<string, string>> = {
  'bottom-center': {
    position: 'fixed', bottom: '60px', left: '50%', transform: 'translateX(-50%)',
  },
  'top-left': {
    position: 'fixed', top: '40px', left: '40px',
  },
  'top-right': {
    position: 'fixed', top: '40px', right: '40px',
  },
  'bottom-left': {
    position: 'fixed', bottom: '60px', left: '40px',
  },
  'bottom-right': {
    position: 'fixed', bottom: '60px', right: '40px',
  },
  'center': {
    position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)',
  },
};

/**
 * Inject content into a zone. Replaces any existing overlay in that zone.
 * Security: contentHtml is generated by template renderers which escape all
 * text fields via escapeHtml(). Content originates from author-controlled
 * manifest files, not end-user input.
 */
export async function injectIntoZone(
  page: Page,
  zone: Zone,
  contentHtml: string,
  containerStyles: Record<string, string>,
  animationCSS?: string,
): Promise<void> {
  const zoneId = ZONE_ID_PREFIX + zone;
  const positionStyles = ZONE_POSITIONS[zone];
  const baseStyles: Record<string, string> = {
    ...positionStyles,
    zIndex: '999999',
    pointerEvents: 'none',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    ...containerStyles,
  };

  await page.evaluate(([id, html, styles, css]) => {
    const existing = document.getElementById(id);
    if (existing) existing.remove();

    if (css) {
      const styleId = id + '-style';
      let styleEl = document.getElementById(styleId) as HTMLStyleElement | null;
      if (!styleEl) {
        styleEl = document.createElement('style');
        styleEl.id = styleId;
        document.head.appendChild(styleEl);
      }
      styleEl.textContent = css;
    }

    const container = document.createElement('div');
    container.id = id;
    container.innerHTML = html;
    Object.assign(container.style, styles);
    document.body.appendChild(container);
  }, [zoneId, contentHtml, baseStyles, animationCSS ?? ''] as const);
}

/**
 * Remove the overlay in the specified zone, if any.
 */
export async function removeZone(page: Page, zone: Zone): Promise<void> {
  const zoneId = ZONE_ID_PREFIX + zone;
  await page.evaluate((id) => {
    document.getElementById(id)?.remove();
    document.getElementById(id + '-style')?.remove();
  }, zoneId);
}
